import { createStore } from './store.mjs';
import { analyzeFieldVisit, analyzeMeeting, analyzePreContact } from './analysis.mjs';
import { calculateRoi } from './business-case.mjs';

const app = document.querySelector('#app');
const store = createStore();
const state = { selectedProjectId: null, selectedCustomerId: null };
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const statusClass = (status) => ({ '확인됨': 'verified', '추정': 'hypothesis', '확인 필요': 'needed', '제안': 'proposal' }[status] ?? 'needed');

function render() {
  const projects = store.listProjects();
  const selectedProject = state.selectedProjectId ? store.getProject(state.selectedProjectId) : null;
  const selectedCustomer = selectedProject ? store.getCustomer(selectedProject.id, state.selectedCustomerId) : null;
  app.innerHTML = `<div class="layout"><aside class="sidebar"><div class="side-title"><span>사업개발 프로젝트</span><button class="icon-button" data-action="new-project">＋</button></div>${projects.length ? projects.map((project) => `<button class="project-item ${project.id === state.selectedProjectId ? 'active' : ''}" data-project="${project.id}"><strong>${escapeHtml(project.companyName)}</strong><small>${project.customers.length}개 고객사 · ${escapeHtml(project.industry || '업종 미지정')}</small></button>`).join('') : '<p class="empty">아직 프로젝트가 없습니다.</p>'}</aside><section class="content">${selectedProject && selectedCustomer ? projectView(selectedProject, selectedCustomer) : welcomeView()}</section></div>`;
  bind();
}

function welcomeView() { return `<div class="welcome"><div class="welcome-mark">◎</div><p class="eyebrow">START WITH WHAT YOU KNOW</p><h2>고객을 만나기 전,<br />사업 기회를 구조화하세요.</h2><p>프로젝트 안에서 여러 고객사를 관리하고, 선택한 고객사별로 자료와 분석을 이어갑니다.</p><button class="primary" data-action="new-project">새 사업개발 프로젝트 만들기 <span>→</span></button></div>`; }

function projectView(project, customer) {
  const verified = customer.results.filter((item) => item.status === '확인됨').length;
  const hypotheses = customer.results.filter((item) => item.status === '추정').length;
  const needed = customer.results.filter((item) => item.status === '확인 필요').length;
  return `<div class="project-header"><div><p class="eyebrow">BUSINESS DEVELOPMENT PROJECT</p><h2>${escapeHtml(project.companyName)}</h2><p class="muted">${project.customers.length}개 고객사 관리 · 선택한 고객사의 분석 화면</p></div><button class="secondary" data-action="analyze">↻ 사전 분석 갱신</button></div><div class="customer-switch"><div><p class="eyebrow">SELECT CUSTOMER</p><select data-customer-select>${project.customers.map((item) => `<option value="${item.id}" ${item.id === customer.id ? 'selected' : ''}>${escapeHtml(item.companyName)} · ${escapeHtml(item.industry || '업종 미지정')}</option>`).join('')}</select></div><button class="primary" data-action="new-customer">＋ 고객사 추가</button></div><div class="stats"><div><b>${customer.materials.length}</b><span>${escapeHtml(customer.companyName)} 자료</span></div><div><b>${verified}</b><span>확인됨</span></div><div><b>${hypotheses}</b><span>추정</span></div><div><b>${needed}</b><span>확인 필요</span></div></div><div class="grid-two"><section class="panel"><div class="panel-heading"><div><p class="eyebrow">SELECTED CUSTOMER</p><h3>${escapeHtml(customer.companyName)}</h3><p class="muted">${escapeHtml(customer.industry || '업종 미지정')} · ${customer.contactStage === 'pre-contact' ? '방문·미팅 전' : '기초 자료 단계'}</p></div><button class="text-button" data-action="material">＋ 자료 추가</button></div>${customer.materials.length ? customer.materials.map((material) => `<article class="material"><div class="material-icon">▤</div><div><strong>${escapeHtml(material.title)}</strong><p>${escapeHtml(material.sourceType)} · ${escapeHtml(material.content.slice(0, 90))}${material.content.length > 90 ? '…' : ''}</p></div></article>`).join('') : '<p class="empty">이 고객사의 회사소개서 또는 미팅 자료를 등록하세요.</p>'}</section><section class="panel"><div class="panel-heading"><div><p class="eyebrow">NEXT QUESTIONS</p><h3>다음 확인 질문</h3></div></div>${customer.results.filter((item) => item.followUpQuestion).map((item) => `<div class="question"><span>?</span><p>${escapeHtml(item.followUpQuestion)}</p></div>`).join('') || '<p class="empty">자료를 등록하면 확인 질문이 생성됩니다.</p>'}</section></div>${fieldStructure(customer)}${businessCaseView(customer)}<section class="panel analysis"><div class="panel-heading"><div><p class="eyebrow">ANALYSIS BOARD</p><h3>${escapeHtml(customer.companyName)} 분석 결과</h3></div><span class="muted">자료 등록 때마다 업데이트</span></div>${customer.results.length ? `<div class="result-grid">${customer.results.map((item) => `<article class="result-card"><div class="result-top"><span class="category">${escapeHtml(item.category)}</span><span class="status ${statusClass(item.status)}">${escapeHtml(item.status)}</span></div><p>${escapeHtml(item.statement)}</p><small>출처 · ${escapeHtml(item.sourceType)}</small></article>`).join('')}</div>` : '<div class="empty large">자료를 등록하면 이 고객사의 분석 결과가 생성됩니다.</div>'}</section>`;
}

function fieldStructure(customer) {
  const results = customer.results.filter((item) => item.category.startsWith('As-Is') || item.category.startsWith('To-Be') || item.category === '기대 변화');
  if (!results.length) return '';
  const card = (item) => `<article class="structure-card"><strong>${escapeHtml(item.category)}</strong><p>${escapeHtml(item.statement)}</p><span class="status ${statusClass(item.status)}">${escapeHtml(item.status)}</span></article>`;
  return `<section class="panel structure"><div class="panel-heading"><div><p class="eyebrow">WORKFLOW STRUCTURE</p><h3>As-Is / To-Be 업무 구조</h3></div><span class="muted">${escapeHtml(customer.companyName)} 현장 진단</span></div><div class="structure-grid"><div><span class="structure-label asis">AS-IS</span>${results.filter((item) => item.category.startsWith('As-Is')).map(card).join('')}</div><div><span class="structure-label tobe">TO-BE</span>${results.filter((item) => !item.category.startsWith('As-Is')).map(card).join('')}</div></div></section>`;
}

function businessCaseView(customer) {
  const roi = customer.roi;
  const poc = customer.poc;
  return `<section class="panel business-case"><div class="panel-heading"><div><p class="eyebrow">BUSINESS CASE</p><h3>ROI · PoC 정의</h3><p class="muted">${escapeHtml(customer.companyName)} 기준</p></div><button class="secondary" data-action="business-case">${roi || poc ? '수정' : '입력'}하기</button></div>${roi ? `<div class="business-metrics"><div><b>${roi.roiPercent}%</b><span>예상 ROI</span></div><div><b>${roi.paybackMonths ?? '-'}개월</b><span>회수 기간</span></div><div><b>${roi.annualBenefit.toLocaleString('ko-KR')}원</b><span>연간 효과</span></div></div>` : '<p class="empty">투자비와 연간 효과를 입력해 ROI를 계산하세요.</p>'}${poc ? `<div class="poc-summary"><strong>PoC 범위</strong><span>${escapeHtml(poc.targetProcess)} · ${escapeHtml(poc.scope)} · ${escapeHtml(poc.duration)}</span><small>성공 기준 · ${escapeHtml(poc.successMetric)}</small></div>` : '<p class="empty">검증할 업무 범위와 성공 기준을 정의하세요.</p>'}</section>`;
}

function modal(type) {
  const html = type === 'project' ? `<div class="modal-backdrop"><form class="modal" data-form="project"><button type="button" class="close" data-action="close">×</button><p class="eyebrow">NEW PROJECT</p><h3>사업개발 프로젝트 만들기</h3><label>첫 고객사명<input name="companyName" required placeholder="예: 한빛전자" /></label><label>업종<input name="industry" placeholder="예: 전자부품 제조" /></label><label>현재 고객 접점<select name="contactStage"><option value="pre-contact">방문·미팅 전</option><option value="basic">기초 자료만 보유</option></select></label><button class="primary" type="submit">프로젝트 생성 →</button></form></div>` : type === 'customer' ? `<div class="modal-backdrop"><form class="modal" data-form="customer"><button type="button" class="close" data-action="close">×</button><p class="eyebrow">NEW CUSTOMER</p><h3>고객사 추가</h3><label>고객사명<input name="companyName" required placeholder="예: 미래정밀" /></label><label>업종<input name="industry" placeholder="예: 정밀 제조" /></label><label>현재 고객 접점<select name="contactStage"><option value="pre-contact">방문·미팅 전</option><option value="basic">기초 자료만 보유</option></select></label><button class="primary" type="submit">고객사 추가 →</button></form></div>` : type === 'business-case' ? `<div class="modal-backdrop"><form class="modal" data-form="business-case"><button type="button" class="close" data-action="close">×</button><p class="eyebrow">BUSINESS CASE</p><h3>ROI · PoC 정의</h3><h4>ROI 가정</h4><label>초기 투자비<input name="investment" type="number" min="0" value="${state.roi?.investment ?? ''}" placeholder="원" /></label><label>연간 비용 절감액<input name="annualSavings" type="number" min="0" value="${state.roi?.annualSavings ?? ''}" placeholder="원" /></label><label>연간 매출 증가액<input name="annualRevenueGain" type="number" min="0" value="${state.roi?.annualRevenueGain ?? ''}" placeholder="원" /></label><h4>PoC 범위</h4><label>대상 업무<input name="targetProcess" value="${state.poc?.targetProcess ?? ''}" placeholder="예: 입고·재고실사" /></label><label>적용 범위<input name="scope" value="${state.poc?.scope ?? ''}" placeholder="예: 1개 공장" /></label><label>성공 기준<input name="successMetric" value="${state.poc?.successMetric ?? ''}" placeholder="예: 재고 오차율 30% 감소" /></label><label>기간<input name="duration" value="${state.poc?.duration ?? ''}" placeholder="예: 8주" /></label><button class="primary" type="submit">ROI·PoC 저장 →</button></form></div>` : `<div class="modal-backdrop"><form class="modal" data-form="material"><button type="button" class="close" data-action="close">×</button><p class="eyebrow">SOURCE MATERIAL</p><h3>선택 고객사 자료 등록</h3><label>자료명<input name="title" required placeholder="예: 회사소개서 2026" /></label><label>자료 유형<select name="sourceType"><option>회사소개서</option><option>공개자료</option><option>미팅 기록</option><option>현장 메모</option><option>담당자 입력</option></select></label><label>내용 또는 요약<textarea name="content" required rows="6" placeholder="자료의 핵심 내용을 붙여 넣으세요."></textarea></label><button class="primary" type="submit">저장하고 즉시 분석 →</button></form></div>`;
  app.insertAdjacentHTML('beforeend', html); bind();
}

function bind() {
  app.querySelectorAll('[data-project]').forEach((button) => button.addEventListener('click', () => { state.selectedProjectId = button.dataset.project; const project = store.getProject(state.selectedProjectId); state.selectedCustomerId = project.customers[0].id; render(); }));
  app.querySelectorAll('[data-customer-select]').forEach((select) => select.addEventListener('change', () => { state.selectedCustomerId = select.value; render(); }));
  app.querySelectorAll('[data-action="new-project"]').forEach((button) => button.addEventListener('click', () => modal('project')));
  app.querySelectorAll('[data-action="new-customer"]').forEach((button) => button.addEventListener('click', () => modal('customer')));
  app.querySelectorAll('[data-action="business-case"]').forEach((button) => button.addEventListener('click', () => { const project = store.getProject(state.selectedProjectId); const customer = store.getCustomer(project.id, state.selectedCustomerId); state.roi = customer.roi; state.poc = customer.poc; modal('business-case'); }));
  app.querySelectorAll('[data-action="material"]').forEach((button) => button.addEventListener('click', () => modal('material')));
  app.querySelectorAll('[data-action="close"]').forEach((button) => button.addEventListener('click', () => button.closest('.modal-backdrop').remove()));
  app.querySelectorAll('[data-action="analyze"]').forEach((button) => button.addEventListener('click', () => { const project = store.getProject(state.selectedProjectId); const customer = store.getCustomer(project.id, state.selectedCustomerId); const retained = customer.results.filter((item) => item.sourceType === '미팅 기록' || item.sourceType === '현장 메모'); store.saveResults(project.id, customer.id, [...analyzePreContact(customer), ...retained]); render(); }));
  app.querySelectorAll('[data-form="project"]').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); const project = store.createProject(Object.fromEntries(new FormData(form))); state.selectedProjectId = project.id; state.selectedCustomerId = project.customers[0].id; render(); }));
  app.querySelectorAll('[data-form="customer"]').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); const customer = store.createCustomer(state.selectedProjectId, Object.fromEntries(new FormData(form))); state.selectedCustomerId = customer.id; render(); }));
  app.querySelectorAll('[data-form="business-case"]').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(form)); const roi = calculateRoi(values); const poc = { targetProcess: values.targetProcess.trim(), scope: values.scope.trim(), successMetric: values.successMetric.trim(), duration: values.duration.trim() }; store.saveBusinessCase(state.selectedProjectId, state.selectedCustomerId, { roi, poc }); state.roi = null; state.poc = null; render(); }));
  app.querySelectorAll('[data-form="material"]').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); const input = Object.fromEntries(new FormData(form)); const project = store.addSourceMaterial(state.selectedProjectId, state.selectedCustomerId, input); const customer = store.getCustomer(project.id, state.selectedCustomerId); const material = customer.materials.at(-1); const results = input.sourceType === '현장 메모' ? analyzeFieldVisit({ ...customer, material }) : input.sourceType === '미팅 기록' ? analyzeMeeting({ ...customer, material }) : analyzePreContact({ ...customer, materials: [material] }); store.appendResults(project.id, customer.id, results); render(); }));
}

render();
